"""empty message

Revision ID: 81231a5b521b
Revises: 7c604d6faa6d
Create Date: 2024-01-15 15:27:46.287444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81231a5b521b'
down_revision: Union[str, None] = '7c604d6faa6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_logs', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'price_logs', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_logs', type_='foreignkey')
    op.drop_column('price_logs', 'product_id')
    # ### end Alembic commands ###
